List<Map<String, dynamic>> transactions = [
  {
    "id": 1,
    "user_id": 2,
    "amount": 200,
    "is_credit": false,
    "status": "successful",
    "trn_ref": "vnjiv94th",
    "account_number": "0138407224775",
    "bank_name": "UBA Bank",
    "account_name": "Applegate Johnson",
    "currency": "N",
    "updated_at": "2023-01-31T14:45:32.000000Z"
  },
  {
    "id": 2,
    "user_id": 2,
    "amount": 160,
    "is_credit": true,
    "status": "successful",
    "trn_ref": "vnjiv94th",
    "account_number": null,
    "bank_name": null,
    "account_name": null,
    "currency": "N",
    "updated_at": "2023-07-02T14:45:32.000000Z"
  },
  {
    "id": 3,
    "user_id": 2,
    "amount": 600,
    "is_credit": true,
    "status": "successful",
    "trn_ref": "vnjiv94th",
    "account_number": null,
    "bank_name": null,
    "account_name": null,
    "currency": "N",
    "updated_at": "2023-01-31T14:45:32.000000Z"
  },
  {
    "id": 4,
    "user_id": 2,
    "amount": 720,
    "is_credit": true,
    "status": "successful",
    "trn_ref": "vnjiv94th",
    "account_number": null,
    "bank_name": null,
    "account_name": null,
    "currency": "N",
    "updated_at": "2023-02-01T14:45:32.000000Z"
  },
  {
    "id": 5,
    "user_id": 2,
    "amount": 290,
    "is_credit": true,
    "status": "successful",
    "trn_ref": "vnjiv94th",
    "account_number": null,
    "bank_name": null,
    "account_name": null,
    "currency": "N",
    "updated_at": "2023-02-07T14:45:32.000000Z"
  },
  {
    "id": 6,
    "user_id": 2,
    "amount": 790,
    "is_credit": true,
    "status": "successful",
    "trn_ref": "vnjiv94th",
    "account_number": null,
    "bank_name": null,
    "account_name": null,
    "currency": "N",
    "updated_at": "2023-02-07T14:45:32.000000Z"
  },
  {
    "id": 7,
    "user_id": 2,
    "amount": 580,
    "is_credit": true,
    "status": "successful",
    "trn_ref": "vnjiv94th",
    "account_number": null,
    "bank_name": null,
    "account_name": null,
    "currency": "N",
    "updated_at": "2023-02-01T14:45:32.000000Z"
  },
];
